[package]
name = "counter-meta"
version = "0.0.0"
authors = [ "Bicarus <hello@bicarus.io>",]
edition = "2018"
publish = false

[dependencies.counter]
path = ".."

[dependencies.elrond-wasm]
version = "0.34.0"

[dependencies.elrond-wasm-debug]
version = "0.34.0"
